// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertTrip = `-- name: InsertTrip :one
INSERT INTO trips
    ( "destination", "owner_email", "owner_name", "starts_at", "ends_at") VALUES
    ( $1, $2, $3, $4, $5)
RETURNING "id"
`

type InsertTripParams struct {
	Destination string
	OwnerEmail  string
	OwnerName   string
	StartsAt    pgtype.Timestamp
	EndsAt      pgtype.Timestamp
}

func (q *Queries) InsertTrip(ctx context.Context, arg InsertTripParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTrip,
		arg.Destination,
		arg.OwnerEmail,
		arg.OwnerName,
		arg.StartsAt,
		arg.EndsAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
